# Занятие 3
# Алгебра
## Решение систем линейных алгебраических уравнений (СЛАУ)

**Библиотека приближенных вычислений numpy**

https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg

In [1]:
import numpy as np
from numpy import linalg

**numpy.linalg**- часть numpy, посвященная линейной алгебре, там содержатся инструменты создания объектов, представляющих матрицы (np.array) и действий с ними.

Создать "матрицу" можно несколькими способами:

1. На основе других структур данных Python, например, list или tuple

2. с помощью специальных функций, возвращающих матрицы определенного вида (ones, zeros, и т.п.)

3. Соединение нескольких матриц, выделение части матрицы и т.п.

4. Считывая данные в виде array с диска компьютера

In [2]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
zeros_5 = np.zeros(5)
ones_3_2 = np.ones((3, 2))
print(A, zeros_5, ones_3_2, sep='\n')

[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##numpy.linalg.solve

https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html

linalg.solve это решатель СЛАУ из N уравнений от N переменных, т.е. матрица левой части квадратная, причем невырожденная.

**Входные данные** - array_like структуры данных, представляющие левую и правую части СЛАУ, например, вложенные списки для левой части и списки для правой или двумерные array для левой части и одномерные array для правой.

linalg.solve возвращает решение СЛАУ как array такой же размерности, как правая часть. Например, если правая часть СЛАУ - одномерный список, то решение будет одномерным array.

### Пример 1.
Рассмотрим СЛАУ
$$
\left\{
\begin{matrix}
2x + 3y - z = 5\\
3x - 2y + z = 2\\
x + y - z = 0
\end{matrix}
\right.
$$
### Способ 1. СЛАУ в виде вложенного списка.
Составим матрицу левой части СЛАУ в виде вложенного списка, вектор правой части в виде обычного списка и вызовем  linalg.solve.

In [8]:
A1 = [[2, 3, -1],
     [3, -2, 1],
     [1, 1, -1]]
b1 = [5, 2, 0]
b2 = [[5], [2], [0]]

for b in (b1, b2):
    x = linalg.solve(A1,  b)
    print(f'x = {x},\ntype(x) = {type(x)}, x.ndim = {x.ndim}, x.shape = {x.shape}')

x = [1. 2. 3.],
type(x) = <class 'numpy.ndarray'>, x.ndim = 1, x.shape = (3,)
x = [[1.]
 [2.]
 [3.]],
type(x) = <class 'numpy.ndarray'>, x.ndim = 2, x.shape = (3, 1)


### Способ 2. СЛАУ виде array

In [9]:
A1 = np.array(A1)
b_ones = np.ones(3)
print(linalg.solve(A1,  b_ones))

[ 0.44444444 -0.22222222 -0.77777778]


## Проверка правильности расчетов.
**Пример 2.**
Рассмотрим СЛАУ
$$
\left\{
\begin{matrix}
5x - 3y + z = 11\\
2x - 2y + z = 7\\
-x + 3y -2z = -10
\end{matrix}
\right.
$$
Найдем решение $X_2$ данной СЛАУ, записанной в виде $AX = b$. Проверим подстановкой, что $AX_2 = b$, для удобства будем проверять эквивалентное условие  $AX_2 - b = \bar 0$.

Для правильеного умножения матриц используем @ вместо привычного * (* приводит к поэлементному перемножению матриц).

In [16]:
A2 = np.array([[5, -3, 1],
               [2, -2, 1],
               [-1, 3, -2]])
b2 = [11, 7, -10]
x2 = linalg.solve(A2,  b2)
print(f'Проверка: AX - b = {A2 @ x2 - b2}')

Проверка: AX - b = [0. 0. 0.]


# Транспонирование array

При транспонировании создается view исходного array, где оси меняются  местами. При изменении транспонированного array изменяется и исходный:

In [21]:
P = np.array([[5, -3, 1],
               [2, -2, 1],
               [-1, 3, -2]])
D = P.T
D[0, 2] = 10
P[1, 2] = 0
print(f'P.T = {D},\nP = {P}')

P.T = [[ 5  2 10]
 [-3 -2  3]
 [ 1  0 -2]],
P = [[ 5 -3  1]
 [ 2 -2  0]
 [10  3 -2]]


Если нужно получить копию транспонированного array, используем метод copy()

In [22]:
R = np.array([[5, -3, 1],
               [2, -2, 1],
               [-1, 3, -2]])
M = R.T.copy()
M[0, 2] = 10
R[1, 0] = 8
print(f'R.T = {M},\nR = {R}')

R.T = [[ 5  2 10]
 [-3 -2  3]
 [ 1  1 -2]],
R = [[ 5 -3  1]
 [ 8 -2  1]
 [-1  3 -2]]


### Пример 3.
Записать в матричном виде СЛАУ
$$
\left\{
\begin{matrix}
x + ky - z = 1\\
2x + y + 3 z = -2\\
-3x + (k - 2)z -3z = 5
\end{matrix}
\right..
$$
Решить СЛАУ при значениях параметра $k = -1, 0, 2, 5$ и выполнить проверку.

Построим матрицу-шаблон, затем в цикле будем придавать нужные значения элементам матрицы левой части, соответствующим значениям параметра.

In [27]:
A3 = np.array([[1, 0, -1],
               [2, 1, 3],
               [-3, -2, -3]])
b3 = np.array([1, -2, 5])

for k in (-1, 0, 2, 5):
    A3k = A3.copy()
    for j in (0, 2):
        A3k[j, 1] += k
    print(f'Ak = {A3k}')
    x = linalg.solve(A3k,  b3)
    print(f'x = {x}, AX - b = {A3k @ x - b3}')

Ak = [[ 1 -1 -1]
 [ 2  1  3]
 [-3 -3 -3]]
x = [-3.33333333e-01 -1.33333333e+00 -1.11022302e-16], AX - b = [-5.55111512e-16 -8.88178420e-16  0.00000000e+00]
Ak = [[ 1  0 -1]
 [ 2  1  3]
 [-3 -2 -3]]
x = [ 1. -4.  0.], AX - b = [0. 0. 0.]
Ak = [[ 1  2 -1]
 [ 2  1  3]
 [-3  0 -3]]
x = [-1.66666667e+00  1.33333333e+00 -1.11022302e-16], AX - b = [-5.55111512e-16 -8.88178420e-16  0.00000000e+00]
Ak = [[ 1  5 -1]
 [ 2  1  3]
 [-3  3 -3]]
x = [-1.22222222e+00  4.44444444e-01 -1.11022302e-16], AX - b = [-3.33066907e-16 -8.88178420e-16  0.00000000e+00]


## Присоединение array в строку или в столбик
$A$ и $B$ типа array можно соединить в строку с помощью np.hstack(),
а для соединения в столбик используется
np.vstack().

In [38]:
A = np.diag([1, 2])
b = np.array([3, 4]).reshape((2, 1))
Ab = np.hstack((A, b))
Ac = np.vstack((A, b.T))
print(f'A ={A}\nb = {b}\nAb = {Ab}\nAc = {Ac}')

A =[[1 0]
 [0 2]]
b = [[3]
 [4]]
Ab = [[1 0 3]
 [0 2 4]]
Ac = [[1 0]
 [0 2]
 [3 4]]


### Выделение строки, столбца и подматрицы в матрице
Для выделения части матрицы будем использовать диапазоны (срезы, slice)

Напомним, что обращение к элементу матрицы осуществляется указанием в квадратных скобках после имени матрицы номера строки и номера столбца через запятую,

например, $А[2, 3]$.

Если нужно выделить элементы строки, стоящие в столбцах с 3 до 5 (не включая 5!), то вместо номера столбца указываем диапазон (срез) 3:5,
двоеточие обозначает, что берутся и все промежуточные индексы.

**!!!ВАЖНО!!!**

В диапазонах не учитывается последнее значение,
так срез 3:5 не включает элемент с номером 5!

Например, можно в матрице $A\_with\_B$ выделить в первой строке элементы, стоящие в столбцах с 1 до 3 (не включая 3!):

In [39]:
Ab[0, 1:3]

array([0, 3])

Выделим столбец с номером 1 в матрице $A$

In [40]:
A[:, 1]

array([0, 2])

Выделим строку с номером 0 в матрице $A$

In [41]:
A[0, :]

array([1, 0])

Выделим часть матрицы $M$, находящуюся в верхних 4 строках и столбцах с 2-го до 5 (не включая 5-й)

In [47]:
M = np.diag(range(7))
print(f'M =\n{M}\nM[0:4, 2:5] =\n{M[0:4, 2:5]}')

M =
[[0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 0 0 4 0 0]
 [0 0 0 0 0 5 0]
 [0 0 0 0 0 0 6]]
M[0:4, 2:5] =
[[0 0 0]
 [0 0 0]
 [2 0 0]
 [0 3 0]]


### Ввод с консоли:

input()

есть необязательный переметр - приглашение к вводу:

In [50]:
numbers_my = input('Введите несколько чисел через пробел: \n')
K = np.array(numbers_my.split(), dtype=int)
print(f'Получился array {K}')

Введите несколько чисел через пробел: 
-1 4 2 100
Получился array [ -1   4   2 100]


### Создание матрицы на основе lambda-функции
Используем анонимную функцию (lambda-функцию)

In [52]:
P = np.fromfunction(lambda i, j: 2 * i + (-1) ** j, (4, 5), dtype=int)
print(f'Получился array\n{P}')

Получился array
[[ 1 -1  1 -1  1]
 [ 3  1  3  1  3]
 [ 5  3  5  3  5]
 [ 7  5  7  5  7]]


### Создание матрицы на основе функции пользователя

In [66]:
def matr(i, j):
    return (i + 2) ** (j + 1)

Q = np.fromfunction(matr, (3, 4), dtype=int)
print(f'Получился array\n{Q}')

Получился array
[[  2   4   8  16]
 [  3   9  27  81]
 [  4  16  64 256]]


In [68]:
def matr(i, j):
    return i == j

G = np.fromfunction(matr, (3, 4))
print(f'Получился array\n{G}')

Получился array
[[ True False False False]
 [False  True False False]
 [False False  True False]]
