# Практическое занятие 8
# Компьютерный практикум по алгебре на Python
## Численное решение систем линейных алгебраических уравнений (СЛАУ) с numpy.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [2]:
import numpy as np
from numpy import linalg
import pandas as pd

from IPython.display import display, Latex, Math
from sympy import latex
# from google.colab import files

### Задание 1.
Решить СЛАУ с помощью linalg.solve() и выполнить проверку.
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+5z=10
\end{matrix}
\right.
$$

In [3]:
A = np.array([[-1, 5, -3], [4, -1, 5], [3, 4, 5]])
b = np.array([8, -1, 10])

slv = linalg.solve(A, b)
display(A @ slv == b)
display(np.allclose(A @ slv, b))

array([ True,  True,  True])

True

### Задание 2.
Определить с помощью Теоремы Кронекера-Капелли и linalg.matrix_rank, совместна ли СЛАУ
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+2z=7
\end{matrix}
\right.
$$

Сделать вывод о числе решений (текстом)

In [5]:
A = np.array([[-1, 5, -3], [4, -1, 5], [3, 4, 2]])
b = np.array([8, -1, 7])

rg_A = linalg.matrix_rank(A)
rg_Ab = linalg.matrix_rank(np.column_stack((A, b)))
display(Latex(fr'$rgA = rgA|b = \text{rg_Ab} \wedge \text{{linalg.solve(A, b) выдает LinAlgError: Singular matrix}} \Rightarrow \text{{СЛАУ имеет более одного решения}}$'))


<IPython.core.display.Latex object>

### Задание 3
В расширенной матрице СЛАУ из Задания 2

1) выделить матрицу левой части

2) выделить столбец правой части

3) транспонировать матрицу, полученную в 1)

4) получить расширенную матрицу из матрицы 3) и столбца 2)

5) создать на основе списочного выражения np.array $3\times 4$ из расположенных в шахматном порядке чисел 1 и $-1$.

In [6]:
Ab = np.column_stack((A, b))

A = Ab[:3, :3]
b = Ab[:3, -1]
A_transposed = np.transpose(A)
expanded = np.column_stack((A_transposed, b))
chess = np.array([[(-1) ** (i + j) for i in range(1, 5)] for j in range(1, 4)])
print('1) ', A, '2)', b, '3)', A_transposed, '4)', expanded, '5)', chess, sep='\n')

1) 
[[-1  5 -3]
 [ 4 -1  5]
 [ 3  4  2]]
2)
[ 8 -1  7]
3)
[[-1  4  3]
 [ 5 -1  4]
 [-3  5  2]]
4)
[[-1  4  3  8]
 [ 5 -1  4 -1]
 [-3  5  2  7]]
5)
[[ 1 -1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]]


### Задание 4.
Исследовать на совместность СЛАУ с параметром $a$ при значениях параметра $a=-1$, $a=0$ и $a=1$ и найти решение, если оно единственно и провести проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+5y-3z=8a\\
4x-ay+5z=-a\\
3x+4y+2z=5a
\end{matrix}
\right.
$$
**Указание** - описать функцию check_SLAE от аргументов $A$ и $b$ (матрица левой части и столбец правой части), которая возвращает 0 для несовместной СЛАУ, 1 для совместной СЛАУ с единственным решением и 2 в остальных случаях.

Затем в цикле по значениям параметра $a$ проверять с помощью check_SLAE совместность и единственность решения СЛАУ и выводить на экран значение параметра и решение СЛАУ, если оно существует и единственно или "решений нет" или "решение не единственно".

In [7]:
def check_SLAE(A, b):
    if linalg.matrix_rank(A) != linalg.matrix_rank(np.column_stack((A, b))):
        return 0
    elif linalg.matrix_rank(A) == linalg.matrix_rank(np.column_stack((A, b))):
        return 1
    
    return 2

for a in [-1, 0, 1]:
    A = np.array([[-1, 5, -3], [4, -a, 5], [3, 4, 2]])
    b = np.array([8 * a, -a, 5 * a])
    
    flag = check_SLAE(A, b)
    if flag == 0:
        print(f'при a = {a} решений нет')
    elif flag == 1:
        print(f'при a = {a} ', linalg.solve(A, b))
    else:
        print(f'при a = {a} решение не единственно')

при a = -1  [-1.28571429 -1.          1.42857143]
при a = 0  [ 0.  0. -0.]
при a = 1 решений нет


### Задание 5.
Считать из файла 'SLAE_5.xlsx' матрицу левой части и столбец правой части с листов 'A5' и 'b5' и вывести их на экран.

Решить СЛАУ $AX=b$ и вывести полученное решение на экран.

Записать полученное решение в файл  'SLAE_5.xlsx' на лист 'X5'.

Скачать полученный файл.

In [ ]:
uploaded = files.upload()
for fn in uploaded.keys():
    print(f'The file {fn} has been uploaded')
    Adf = pd.read_excel(fn, sheet_name='A5', header=None)
    bdf = pd.read_excel(fn, sheet_name='b5', header=None)
    print(A, b, sep='\n')

A = Adf.to_numpy()
b = bdf.to_numpy()

X = linalg.solve(A_arr, b_arr)
Xdf = pd.DataFrame(X)
with pd.ExcelWriter(fn, mode='a') as writer:
    Xdf.to_excel(writer, sheet_name='X5', header=False, index=False)

files.download(fn)

### Индивидуальное задание.
Исследовать на совместность СЛАУ с параметром $a$ при заданных значениях параметра $a$ и найти решение, если оно единственно и провести проверку подстановкой.

На листы 'A1', 'A2' и т.п. файла 'Name_Ind_8_SLAE.xlsx' записать матрицы при заданных значениях параметра $a$, на листы 'b1', 'b2' и т.п. столбцы правой части СЛАУ, на листы 'X1', 'X2' и т.п. решения СЛАУ (если оно существует!).


N 175
\begin{align*}
 A = \left[\begin{matrix}4 & a & -7 & 8\\-3 & 5 & -7 & -9\\0 & -3 & 8 & -5\\-15 & -19 & 14 & -33\end{matrix}\right],
    \qquad b = \left[\begin{matrix}-20\\-45\\37\\27\end{matrix}\right], \alpha = 2, \alpha = 8, \alpha = 9.
 \end{align*}

In [ ]:
uploaded = files.upload()

for name in uploaded.keys():
    with pd.ExcelWriter(name, mode='w') as f:
        a = [2, 8, 9]
        for i in range(len(a)):
            A = np.array([[4, a[i], -7, 8], [-3, 5, -7, -9], [0, -3, 8, -5], [-15, -19, 14, -33]])
            b = np.array([-20, -45, 37, 27])

            Adf = pd.DataFrame(A)
            Adf.to_excel(f, sheet_name='A' + str(i + 1), header=False, index=False)

            bdf = pd.DataFrame(b)
            bdf.to_excel(f, sheet_name='b' + str(i + 1), header=False, index=False)

            if linalg.matrix_rank(A) == linalg.matrix_rank(np.column_stack((A, b))):
                X = linalg.solve(A, b)
                Xdf = pd.DataFrame(X)
                Xdf.to_excel(f, sheet_name='X' + str(i + 1), header=False, index=False)
    files.download(name)